#!/usr/bin/env bash


### Create a database backup.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) mysql backup


set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


message_welcome "Backing up the '${MYSQL_DATABASE}' database..."


if [[ "${MYSQL_USER}" == "mysql" ]]; then
    message_error "Backing up as 'mysql' user is not supported. Assign 'MYSQL_USER' env with another one and try again."
    exit 1
fi

export PGHOST="${MYSQL_HOST}"
export PGPORT="${MYSQL_PORT}"
export PGUSER="${MYSQL_USER}"
export PGPASSWORD="${MYSQL_PASSWORD}"
export PGDATABASE="${MYSQL_DATABASE}"

backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"
mysqldump | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"

message_success "'${MYSQL_DATABASE}' database backup '${backup_filename}' has been created and placed in '${BACKUP_DIR_PATH}'."
