#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"


#if [ -z "${POSTGRES_USER}" ]; then
#    base_postgres_image_default_user='postgres'
#    export POSTGRES_USER="${base_postgres_image_default_user}"
#fi
#if [ -z "${MYSQL_USER}" ]; then
#    base_mysql_image_default_user='account'
#    export MYSQL_USER="${base_mysql_image_default_user}"
#fi
#export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"

python << END
import sys
import time
import pymysql

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        pymysql.connect(host="${MYSQL_HOST}",
        user="${MYSQL_USER}",
        password="${MYSQL_PASSWORD}",
        database="${MYSQL_DATABASE}",
        )
        break
    except pymysql.OperationalError as error:
        sys.stderr.write("Waiting for Mysql to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

#while True:
#    try:
#        psycopg2.connect(
#            dbname="${POSTGRES_DB}",
#            user="${POSTGRES_USER}",
#            password="${POSTGRES_PASSWORD}",
#            host="${POSTGRES_HOST}",
#            port="${POSTGRES_PORT}",
#        )
#        break
#    except psycopg2.OperationalError as error:
#        sys.stderr.write("Waiting for PostgreSQL to become available...\n")
#
#        if time.time() - start > suggest_unrecoverable_after:
#            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))
#
#    time.sleep(1)
#END
#>&2 echo 'PostgreSQL is available'
>&2 echo 'Mysql is available'

exec "$@"
