#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"


#if [ -z "${POSTGRES_USER}" ]; then
#    base_postgres_image_default_user='postgres'
#    export POSTGRES_USER="${base_postgres_image_default_user}"
#fi
#if [ -z "${MYSQL_USER}" ]; then
#    base_mysql_image_default_user='account'
#    export MYSQL_USER="${base_mysql_image_default_user}"
#fi
#export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"
echo $DATABASE_URL

mysql_ready() {
python << END
import sys
import mysql.connector

try:
    mysql.connector.connect(
      host="${MYSQL_HOST}",
      user="${MYSQL_USER}",
      password="${MYSQL_PASSWORD}",
      database="${MYSQL_DATABASE}",
    )
except Exception as e:
    print('Exception at entrypoint file', e)
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 1
done
>&2 echo 'Mysql is available'

exec "$@"
